# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: ultralytics_yolo
description: Flutter plugin for Ultralytics YOLO computer vision models on desktop platforms (Windows, Linux, macOS, Web).
version: 0.6.0
homepage: https://github.com/Maicarons/yolo-flutter-app-desktop
repository: https://github.com/Maicarons/yolo-flutter-app-desktop
issue_tracker: https://github.com/Maicarons/yolo-flutter-app-desktop/issues

topics:
  - computer-vision
  - object-detection
  - yolo
  - machine-learning
  - flutter-plugin
  - desktop

funding:
  - https://github.com/sponsors/ultralytics

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path_provider: ^2.1.5
  plugin_platform_interface: ^2.1.8
  shared_preferences: ^2.2.0
  url_launcher: ^6.3.2
  wakelock_plus: ^1.2.0
  web: ^1.1.1

dev_dependencies:
  coverage: ^1.15.0
  flutter_lints: ">=5.0.0 <7.0.0"
  flutter_test:
    sdk: flutter
  mockito: ^5.6.4
  very_good_analysis: ">=6.0.0 <11.0.0"

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: YoloPlugin
      linux:
        pluginClass: YoloPlugin
      macos:
        pluginClass: YoloPlugin
      web:
        pluginClass: YoloPluginWeb
        fileName: ultralytics_yolo_web.dart
  assets:
    - assets/ultralytics_yolo_logotype.png
    - assets/focus_reticle.png
